// Selected work is credited to each founder, not to the newly formed studio.
// Source records distinguish client commissions from personal research and studies.
export const PROJECTS = [
  {
    id: "ran-bring-your-love",
    title: "OFFER NISSIM — BRING YOUR LOVE",
    founder: "Ran Bensimon",
    category: "AI film & live visuals",
    services: ["film", "pipeline", "art"],
    image: "studio/ran-bring-your-love.webp",
    source: "https://ranbensimon.com/offer-nissim-bring-your-love/",
    watchUrl: "https://www.youtube.com/watch?v=MTHS7tPVhaA",
    embedId: "MTHS7tPVhaA",
    type: "commission",
    summary: "An eight-minute opening film for Offer Nissim's show, designed for two transparent LED walls and subsequently released as an official music video. Ran developed the concept, generated the imagery, edited and finished the film.",
    role: "Video art · Concept · AI generation · Edit · Finishing",
    year: 2026,
    outputs: ["Eight-minute show film", "Two transparent LED walls", "Official music video"],
    stack: ["GPT Image 2", "Seedance 2.5", "Local finishing"],
    collaborators: "Yossi Madar — art direction and graphic design; Offer Nissim — music production",
  },
  {
    id: "ran-omer-adam",
    title: "OMER ADAM LIVE SHOW",
    founder: "Ran Bensimon",
    category: "Real-time performance visuals",
    services: ["3d", "film"],
    image: "studio/ran-omer-adam.webp",
    source: "https://ranbensimon.com/omer-adam/",
    watchUrl: "https://www.youtube.com/watch?v=scT3LCzYdXw",
    embedId: "scT3LCzYdXw",
    type: "commission",
    summary: "Unreal Engine stage visuals for Omer Adam's 2025 live show, conformed to the venue's screen layout and timed to the setlist. Characters, choreography, materials, lighting and effects form a coordinated concert system.",
    role: "Real-time direction · MetaHuman work · Control Rig animation · Lookdev · Material blueprints · VFX",
    year: 2025,
    outputs: ["Large-format stage-screen content", "Setlist-timed visual sequences"],
    stack: ["Unreal Engine", "MetaHumans", "Control Rigs", "Material Blueprints", "Niagara VFX"],
  },
  {
    id: "ran-coastcity",
    title: "COASTCITY — FUTURO",
    founder: "Ran Bensimon",
    category: "Volumetric music video",
    services: ["3d", "film"],
    image: "studio/ran-coastcity.webp",
    source: "https://ranbensimon.com/coastcity-volumetric-video/",
    watchUrl: "https://www.youtube.com/watch?v=bHtxzQ_-7Dc",
    embedId: "bHtxzQ_-7Dc",
    type: "commission",
    summary: "A volumetric music video made with YOOM for CoastCity's Futuro. A Miami-inspired Unreal Engine environment combines captured performers, real-time water, lighting and audio-reactive shaders.",
    role: "Environment design · Cinematography · VFX · Lighting · Audio-reactive shaders",
    year: 2023,
    outputs: ["Volumetric music video"],
    stack: ["Unreal Engine", "Volumetric capture", "Real-time fluid simulation"],
  },
  {
    id: "ran-ltx",
    title: "3D → STYLIZED",
    founder: "Ran Bensimon",
    category: "Controlled AI video pipeline",
    services: ["pipeline", "3d", "film"],
    image: "studio/ran-ltx.webp",
    source: "https://ranbensimon.com/ltx-ic-lora-keyframes/",
    watchUrl: "https://www.youtube.com/watch?v=8I4Ps3pS4MQ",
    embedId: "8I4Ps3pS4MQ",
    type: "research",
    summary: "A personal fan-art R&D study translating a rough 3D sequence into stylized animation. Structural controls and reference keyframes guide motion, composition and character consistency through a custom ComfyUI workflow.",
    role: "Pipeline design · Workflow engineering · Lookdev · Direction",
    year: 2026,
    outputs: ["102-second comparison reel", "2688 × 1536 workflow breakdown"],
    stack: ["LTX-2.3", "IC-LoRA", "ComfyUI", "DWPose", "DepthCrafter", "Canny", "Python"],
    note: "Personal fan-art and R&D. The showcase character remains the property of its rights holders.",
  },
  {
    id: "ran-ad-astra",
    title: "AD ASTRA",
    founder: "Ran Bensimon",
    category: "Art installation",
    services: ["art", "3d", "film"],
    image: "studio/ran-ad-astra.webp",
    source: "https://ranbensimon.com/ad-astra/",
    watchUrl: "https://www.youtube.com/watch?v=YvpGefdMuN0",
    embedId: "YvpGefdMuN0",
    type: "commission",
    summary: "An art installation collaboration with Guillaume Thomas, produced by Le Fresnoy and exhibited at Panorama 24. Character look development, procedural environments and cinematic composition move between portrait and cosmographic scale.",
    role: "Co-direction · 3D visualization · Lookdev · Cinematic composition",
    year: 2023,
    outputs: ["Art installation", "Panorama 24 exhibition"],
    stack: ["Real-time 3D pipelines", "Offline 3D pipelines"],
    collaborators: "Guillaume Thomas; produced by Le Fresnoy — Studio national des arts contemporains",
    note: "The source dates the work 2022–2023; the portfolio index lists 2023.",
  },
  {
    id: "ran-neon-dojo",
    title: "NEON DOJO",
    founder: "Ran Bensimon",
    category: "Playable browser experience",
    services: ["web", "pipeline", "art"],
    image: "studio/ran-neon-dojo.png",
    source: "https://ranbensimon.com/neon-dojo-fight/",
    playUrl: "https://neon-dojo-fight.pages.dev/",
    type: "research",
    summary: "An open-source browser fighting game built in Phaser. A local AI pipeline produces the character art, animation assets, sound effects and music, while a custom fight system carries the interactive experience.",
    role: "Game design · Fight-system engineering · Local AI asset pipeline · Generated art and audio direction",
    year: 2026,
    outputs: ["Playable browser game", "AI-generated art and audio", "Open-source repository"],
    stack: ["Phaser 3", "TypeScript", "Vite", "ComfyUI", "Qwen-Image", "Stable Audio Open", "ACE-Step", "Cloudflare Pages"],
    repository: "https://github.com/rbs250/fighting-game",
    note: "Independent open-source project.",
  },
  {
    id: "dor-ai-film",
    title: "AI FILM STUDY",
    founder: "Dor Fellous",
    category: "AI film",
    services: ["film", "art"],
    image: "studio/dor-film-01.jpeg",
    source: "https://www.instagram.com/reel/DSjnqRxiBbZ/",
    watchUrl: "https://www.instagram.com/reel/DSjnqRxiBbZ/",
    type: "study",
    summary: "An AI film from Dor's published selected-work portfolio, with direction and concept credited to Dor Fellous.",
    role: "Direction · Concept",
    year: null,
    outputs: ["AI film", "Instagram reel"],
    stack: [],
  },
  {
    id: "dor-digital-fashion",
    title: "DIGITAL FASHION STUDY",
    founder: "Dor Fellous",
    category: "Digital fashion",
    services: ["3d", "film", "art"],
    image: "studio/dor-fashion-02.jpeg",
    video: "studio/dor-fashion-02.mp4",
    source: "https://www.instagram.com/reel/DUxdDQoCBVj/",
    watchUrl: "https://www.instagram.com/reel/DUxdDQoCBVj/",
    type: "study",
    summary: "A digital fashion film from Dor's selected-work portfolio, with direction and concept credited to Dor Fellous.",
    role: "Direction · Concept",
    year: null,
    outputs: ["Digital fashion film", "Instagram reel"],
    stack: [],
  },
  {
    id: "dor-object-001",
    title: "OBJECT 001 — EYEWEAR",
    founder: "Dor Fellous",
    category: "Wearable object",
    services: ["3d", "art"],
    image: "product-heat-four-lens-v3.png",
    source: "https://dorfellous.github.io/dfrbs-studio-object-001/?object=001",
    type: "object",
    summary: "Biomorphic eyewear defined by four convex bubble lenses and a narrow organic bridge. A limited-number, 3D-printed object offered in BLACK, PEARL and HEAT.",
    role: "Wearable object design",
    year: null,
    outputs: ["Four-lens eyewear", "BLACK, PEARL and HEAT colorways"],
    stack: ["3D printing"],
  },
];

export const FOUNDERS = [
  {
    id: "ran-bensimon",
    name: "Ran Bensimon",
    role: "Creative technologist · Creative AI specialist",
    description: "Ran works across real-time 3D, generative AI and filmmaking. His practice includes characters and virtual garments, live visuals, AI workflow engineering, interactive experiences and teaching.",
    source: "https://ranbensimon.com/",
    email: "info@ranbensimon.com",
  },
  {
    id: "dor-fellous",
    name: "Dor Fellous",
    role: "AI films · Digital fashion · Wearable art",
    description: "Dor creates AI films, digital fashion and wearable art, with direction and concept at the centre of his practice. His work moves between authored images, the body and sculptural form.",
    source: "https://dor-fellous-portfolio.drktch.chatgpt.site/",
  },
];
