export const SERVICES = [
  {
    key: "film",
    number: "01",
    title: "Films & campaigns",
    summary: "A visual idea, carried through to the final frame.",
    description: "Campaign films, music visuals and short-form series shaped around a clear concept. We can develop the visual language, create the images and bring the edit together for the way the work will be seen.",
    scope: ["Concept, treatment and visual development", "AI and 3D image-making, animation and compositing", "Editing, finishing and versions for agreed formats"],
    outputs: ["A visual treatment and selected keyframes", "A finished film or short-form series", "Exports for the agreed channels or screen layouts"],
    fit: "Brands developing a campaign; artists releasing music; teams creating live-show visuals.",
    inputs: "Your brief, audience, brand assets or music, visual references and intended viewing formats.",
    proofLinks: [
      { label: "Bring Your Love", project: "ran-bring-your-love" },
      { label: "AI Film Study", project: "dor-ai-film" },
    ],
  },
  {
    key: "3d",
    number: "02",
    title: "3D & digital fashion",
    summary: "Characters, garments and objects with their own presence.",
    description: "We develop digital looks, characters and sculptural objects through form, material and movement. The scope can stay on screen or extend into a printed wearable prototype where the project calls for a physical object.",
    scope: ["Silhouette, character and garment development", "3D modeling, materials, lighting and look development", "Animation, renders and wearable-object prototyping"],
    outputs: ["Visual studies and selected 3D assets", "Rendered stills or moving-image sequences", "A printed object prototype when fabrication is part of the scope"],
    fit: "Fashion and accessory brands; artists developing a character or world; cultural projects exploring digital and physical form.",
    inputs: "References, a use case, existing designs or assets, and any physical dimensions or production constraints.",
    proofLinks: [
      { label: "Digital Fashion Study", project: "dor-digital-fashion" },
      { label: "Object 001 — Eyewear", project: "dor-object-001" },
      { label: "Omer Adam Live Show", project: "ran-omer-adam" },
    ],
  },
  {
    key: "web",
    number: "03",
    title: "Websites & creative tools",
    summary: "Places to show the work. Tools to move it forward.",
    description: "Websites, browser experiences and focused creative utilities. We connect visual direction with a working interface, whether the project is a portfolio, a campaign destination, a playable prototype or a tool for a particular task.",
    scope: ["Website structure, interface design and development", "Interactive browser experiences and prototypes", "Creative utilities built around a defined workflow"],
    outputs: ["A working website, browser experience or tool", "Project files and implementation notes", "Handover and launch steps agreed for the project"],
    fit: "Brands launching a campaign; artists presenting a practice; cultural organisations opening an experience to an audience.",
    inputs: "The audience and task, your content and assets, examples you respond to, and any hosting or integration requirements.",
    proofLinks: [
      { label: "Neon Dojo", project: "ran-neon-dojo" },
    ],
  },
  {
    key: "pipeline",
    number: "04",
    title: "AI production workflows",
    summary: "Turn an experiment into a process your team can use.",
    description: "A practical workflow for creating and finishing images or video around your production needs. We can map the process, build the steps, test them on real material and document how the team will run the next iteration.",
    scope: ["Review the current process and define the production task", "Build and test generation, conditioning and finishing steps", "Document reusable settings and transfer the working method"],
    outputs: ["A working workflow with an example run", "Reusable setup files and process notes", "A handover or guided walkthrough for the team"],
    fit: "Creative studios, brand content teams and cultural production teams working with repeated image or video tasks.",
    inputs: "A representative task, sample source material, the current tool setup and the decisions the team needs to control.",
    proofLinks: [
      { label: "3D → Stylized", project: "ran-ltx" },
    ],
  },
  {
    key: "art",
    number: "05",
    title: "Art & experiences",
    summary: "Moving images, objects and interactions for a shared world.",
    description: "An open collaboration around an artwork, exhibition or audience experience. We develop visual worlds and contribute moving images, 3D scenes, objects or interactive prototypes in conversation with the artistic idea and its setting.",
    scope: ["Concept development and visual research", "Moving-image, 3D and sculptural contributions", "Screen-based experiences and exhibition prototypes"],
    outputs: ["A developed visual direction or treatment", "The artwork assets or prototype agreed in the brief", "Presentation files and technical notes for the intended setting"],
    fit: "Artists, curators, cultural organisations and brands commissioning an authored experience.",
    inputs: "The artistic question, the audience and setting, any collaborators, and the space or screen constraints.",
    proofLinks: [
      { label: "Ad Astra", project: "ran-ad-astra" },
      { label: "Object 001 — Eyewear", project: "dor-object-001" },
    ],
  },
  {
    key: "workshop",
    number: "06",
    title: "Workshops & team training",
    summary: "Learn by making something relevant to your practice.",
    description: "Practical sessions around creative AI, 3D and image-to-video methods. We shape the session around the team's starting point and use a concrete exercise to make the process understandable, usable and open to further experimentation.",
    scope: ["Define the team's learning question and starting level", "Prepare a hands-on exercise using a relevant creative task", "Walk through the process, decisions and next experiments"],
    outputs: ["A session plan and practical exercises", "Example files and workflow notes", "A set of suggested next experiments"],
    fit: "Brand and studio teams, artists, cultural organisations and creative-education groups.",
    inputs: "The team's experience, the questions they want to explore, available tools and a useful sample task.",
    proofLinks: [
      { label: "Workflow breakdown", project: "ran-ltx" },
    ],
  },
];
